version: "3"

networks:
  nitter:

services:
  # proxy:
  #   hostname: nitter-proxy
  #   container_name: nitter-proxy
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile
  #   environment:
  #     HOST: "0.0.0.0"
  #     PORT: "8080"
  #     NITTER_BASE_URL: "http://nitter:8080"
  #     CONCURRENCY: "1"
  #   ports:
  #     - "8002:8080"
  #   networks:
  #     - nitter

  nitter:
    build: .
    container_name: nitter
    hostname: nitter
    ports:
      - "8002:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./guest_accounts.json:/src/guest_accounts.json:Z,ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - nitter

  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - nitter

volumes:
  nitter-redis:
